# Tensors

In [2]:
# !pip install torch --upgrade
# !pip install accelerate

In [3]:
!nvidia-smi

Mon Mar 10 09:56:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
import numpy as np
from accelerate import Accelerator

In [5]:
# 2 dimensions
x = torch.empty(2,3)

print(x)

tensor([[ 2.4356e+24, -2.2036e+29,  2.5054e-38],
        [-8.4954e+29,  2.5054e-38,  2.4359e+24]])


In [6]:
# 3 dimensions tensor
y = torch.empty(3,2,3)

print(y)

tensor([[[4.1830e+32, 4.3939e-41, 3.5540e-34],
         [0.0000e+00, 3.3631e-43, 1.8217e-44]],

        [[1.4013e-45, 0.0000e+00, 3.8956e-34],
         [0.0000e+00, 3.8955e-34, 0.0000e+00]],

        [[2.8026e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 4.3938e-41]]])


# Initializing a tensor Directly from data

In [7]:
data = [[1,2], [3,4]]

In [8]:
data

[[1, 2], [3, 4]]

In [9]:
x_data = torch.tensor(data)

# From Numpy array

In [10]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [11]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

# From another Tensor

In [12]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.9559, 0.8301],
        [0.0698, 0.5219]])

# with random or constant values

In [14]:
shape = (2,3)

In [15]:
shape

(2, 3)

In [16]:
random_tensor = torch.rand(shape)
random_tensor

tensor([[0.0740, 0.2854, 0.6863],
        [0.9899, 0.4097, 0.5511]])

In [17]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Attributes of a Tensor

attributes describe shape, datatype and the device on which they are stored

In [19]:
tensor = torch.rand(3,4)
tensor

tensor([[0.6561, 0.9848, 0.8472, 0.9918],
        [0.3048, 0.4323, 0.1134, 0.3283],
        [0.3168, 0.4082, 0.0399, 0.2663]])

In [20]:
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device} ")

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu 


# Moving tensor to the current accelerator if available

In [21]:
accelerator = Accelerator() # Instantiate Accelerator

In [22]:
# Move tensor to the accelerator device
if accelerator.is_local_main_process:  # Check if it's the main process
    tensor = tensor.to(accelerator.device)

In [23]:
# checking where the tensor is
print(tensor.device)

cuda:0


# Standard numpy-like indexing and slicing

In [24]:
# Rows, Columns (3,4) --> 3 Rows, 4 Columns

In [25]:
tensor = torch.ones(4, 4)

In [26]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
print(f"First row: {tensor[0]}")
print(f"First columns: {tensor[:, 0]}")
print(f"Last columns: {tensor[..., -1]}")

First row: tensor([1., 1., 1., 1.])
First columns: tensor([1., 1., 1., 1.])
Last columns: tensor([1., 1., 1., 1.])


In [28]:
# turn second column to zeros
tensor[:, 1] = 0

In [29]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# Joining Tensors

torch.cat and torch.stack

In [30]:
t1 = torch.cat([tensor, tensor, tensor ], dim =1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


# Arithmetic Operations

computing matrix multiplication between two tensors

tensor.T returns the transpose of a tensor

 matrix multiplication https://www.mathsisfun.com/algebra/matrix-multiplying.html

 calculating determinant https://www.mathsisfun.com/algebra/matrix-determinant.html

Rows * columns

In [31]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
# @ dotproduct or matmul
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [34]:
# MatMul - matrix multiplication
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

Returns a tensor with the same size as input that is filled with random numbers from a uniform distribution on the interval [0,1]

In [35]:
y3 = torch.rand_like(tensor)

In [36]:
y3

tensor([[0.6357, 0.2754, 0.9128, 0.4744],
        [0.9548, 0.6968, 0.8462, 0.8831],
        [0.7220, 0.4120, 0.3914, 0.4173],
        [0.5631, 0.3499, 0.0487, 0.6010]])

In [37]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

# Compute Element wise product -  Hadamard product

In [42]:
# * element wise multiplication
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [45]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.5577, 0.5185, 0.3308, 0.8129],
        [0.1070, 0.2950, 0.7195, 0.9869],
        [0.6308, 0.9426, 0.0575, 0.2046],
        [0.0334, 0.9019, 0.1662, 0.0748]])

In [46]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

# Single tensor elemnt to numerical value

In [48]:
agg = tensor.sum()
agg

tensor(12.)

In [51]:
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


# Inplace Operations

They store the result into the operand. They are denoted by a _suffix

They save some memory, but are problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged

In [53]:
print(f"{tensor}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [54]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [55]:
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Tensor to NumPy array

In [57]:
t = torch.ones(5)

In [58]:
t

tensor([1., 1., 1., 1., 1.])

In [59]:
n = t.numpy ()
n

array([1., 1., 1., 1., 1.], dtype=float32)

A change in the tensor reflects in the NumPy array

In [61]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [62]:
t

tensor([2., 2., 2., 2., 2.])

In [63]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

# NumPy array to Tensor

In [65]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [67]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

changes in numpy array reflects in the tensor

In [71]:
np.add(n, 1, out=n)
n

array([3., 3., 3., 3., 3.])